version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb-restaurant
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - the_net
  mongo-express:
    image: mongo-express
    container_name: mongo-express-restaurant
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - the_net
  restaurant-api:
    image: restaurant-api
    container_name: restaurant-api
    restart: always
    ports:
      - "9090:9090"
    networks:
      - the_net

volumes:
  data: {}

networks:
  the_net:
